# ブランド名（重複なし）
SELECT_DISTINCT_BRAND_NAME = "SELECT DISTINCT BRAND_NAME FROM LIP_MASTER WHERE HIDDEN_FLAG != '1';"

# リップ情報取得（リップID)
SELECT_WHERE_LIP_ID = "SELECT * FROM LIP_MASTER WHERE LIP_ID = %(lipId)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（ブランド名)
SELECT_WHERE_BRAND_NAME = "SELECT * FROM LIP_MASTER WHERE BRAND_NAME = %(brandName)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（ブランド名＆カラーコード）
SELECT_WHERE_BRAND_COLORCODE = "SELECT * FROM LIP_MASTER WHERE BRAND_NAME = %(brandName)s AND COLORCODE = %(colorCode)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（同一色）
SELECT_WHERE_COLORCODE = "SELECT * FROM LIP_MASTER WHERE COLORCODE = %(colorCode)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（類似色）
SELECT_WHERE_SIMILAR_COLORCODE = "SELECT * FROM LIP_MASTER WHERE (COLORCODE >= %(downVCode)s AND COLORCODE <= %(upVCode)s) OR (COLORCODE >= %(downSCode)s AND COLORCODE <= %(upSCode)s) AND HIDDEN_FLAG != '1';"

# リップタグ情報取得
SELECT_WHERE_LIP_TAG = "SELECT * FROM LIP_TAG_MAP_MASTER tm JOIN LIP_TAG_MASTER t ON tm.TAG_ID = t.ID WHERE tm.LIP_ID = %(lipId)s AND tm.HIDDEN_FLAG != '1';"

# タグ（重複なし）
SELECT_DISTINCT_TAG_NAME = "SELECT DISTINCT * FROM LIP_TAG_MASTER WHERE HIDDEN_FLAG != '1';"

# ロゴブランド画像（重複なし）
SELECT_DISTINCT_LOGO_IMAGE = "SELECT DISTINCT * FROM `IMAGE_MASTER` WHERE IMAGE_GENRE = '0' AND HIDDEN_FLAG != '1';"

# 商品画像取得
SELECT_WHERE_LIP_IMAGE = "SELECT * FROM LIP_IMAGE_MAP_MASTER im JOIN IMAGE_MASTER i ON im.IMAGE_ID = i.ID WHERE im.LIP_ID = %(lipId)s AND im.HIDDEN_FLAG != '1';"
