# 認証
SELECT_AUTH = 'SELECT HASH_KEY FROM AUTH_MASTER WHERE ACCESS_ID = %(accessId)s'

# ブランド名（重複なし）
SELECT_DISTINCT_BRAND_NAME = "SELECT DISTINCT BRAND_NAME FROM LIP_MASTER WHERE HIDDEN_FLAG != '1';"

# リップ情報取得（リップID)
SELECT_WHERE_LIP_ID = "SELECT * FROM LIP_MASTER WHERE LIP_ID = %(lipId)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（ブランド名)
SELECT_WHERE_BRAND_NAME = "SELECT * FROM LIP_MASTER WHERE BRAND_NAME = %(brandName)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（ブランド名＆カラーコード）
SELECT_WHERE_BRAND_COLORCODE = "SELECT * FROM LIP_MASTER WHERE BRAND_NAME = %(brandName)s AND COLORCODE = %(colorCode)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（同一色）
SELECT_WHERE_COLORCODE = "SELECT * FROM LIP_MASTER WHERE COLORCODE = %(colorCode)s AND HIDDEN_FLAG != '1';"

# リップ情報取得（類似色）
SELECT_WHERE_SIMILAR_COLORCODE = "SELECT * FROM LIP_MASTER WHERE (COLORCODE >= %(downVCode)s AND COLORCODE <= %(upVCode)s) OR (COLORCODE >= %(downSCode)s AND COLORCODE <= %(upSCode)s) AND HIDDEN_FLAG != '1';"

# リップタグ情報取得
SELECT_WHERE_LIP_TAG = "SELECT * FROM LIP_TAG_MAP_MASTER tm JOIN LIP_TAG_MASTER t ON tm.TAG_ID = t.ID WHERE tm.LIP_ID = %(lipId)s AND tm.HIDDEN_FLAG != '1';"

# タグ（重複なし）
SELECT_DISTINCT_TAG_NAME = "SELECT DISTINCT * FROM LIP_TAG_MASTER WHERE HIDDEN_FLAG != '1';"

# ロゴブランド画像（重複なし）
SELECT_DISTINCT_LOGO_IMAGE = "SELECT DISTINCT * FROM `IMAGE_MASTER` WHERE IMAGE_GENRE = '0' AND HIDDEN_FLAG != '1';"

# 商品画像取得
SELECT_WHERE_LIP_IMAGE = "SELECT * FROM LIP_IMAGE_MAP_MASTER im JOIN IMAGE_MASTER i ON im.IMAGE_ID = i.ID WHERE im.LIP_ID = %(lipId)s AND im.HIDDEN_FLAG != '1';"

# カラーコードの検索回数をカウント（新規の場合は追加）
INSERT_UPDATE_COLORCODE_COUNT = "INSERT INTO SEARCH_COLORCODE (COLORCODE, COUNT) VALUES (%(colorCode)s, 1) ON DUPLICATE KEY UPDATE COUNT = COUNT + 1, LAST_SEARCH = CURRENT_TIMESTAMP;"

# 検索履歴管理（カラーコード）
INSERT_COLORCODE_SEARCH_HISTORY = "INSERT INTO SEARCH_COLORCODE_HISTORY (SEARCH_COLORCODE_ID) SELECT ID FROM SEARCH_COLORCODE WHERE COLORCODE = %(colorCode)s;"

# ランキング取得（カラーコード）
SELECT_RANKING_OF_WEEK = "SELECT c.COLORCODE, COUNT(h.ID) AS count FROM SEARCH_COLORCODE c JOIN SEARCH_COLORCODE_HISTORY h ON l.ID = h.SEARCH_LIP_ID_ID WHERE h.SEARCH_TIME >= DATE_SUB(CURDATE(), INTERVAL %(interval)s(CURDATE()) DAY) GROUP BY c.COLORCODE ORDER BY COUNT DESC LIMIT 10;"

# リップの検索回数をカウント（新規の場合は追加）
INSERT_UPDATE_LIP_COUNT = "INSERT INTO SEARCH_LIP (LIP_ID, COUNT) VALUES (%(lipId)s, 1) ON DUPLICATE KEY UPDATE COUNT = COUNT + 1, LAST_SEARCH = CURRENT_TIMESTAMP;"

# 検索履歴管理（リップ）
INSERT_LIP_SEARCH_HISTORY = "INSERT INTO SEARCH_LIP_HISTORY (SEARCH_LIP_ID_ID) SELECT ID FROM SEARCH_LIP WHERE LIP_ID = %(lipId)s;"

# ランキング取得（リップ）
SELECT_RANKING_LIP = "SELECT l.LIP_ID, COUNT(h.ID) AS count FROM SEARCH_LIP l JOIN SEARCH_LIP_HISTORY h ON l.ID = h.SEARCH_LIP_ID_ID WHERE h.SEARCH_TIME >= DATE_SUB(CURDATE(), INTERVAL %(interval)s(CURDATE()) DAY) GROUP BY l.LIP_ID ORDER BY COUNT DESC LIMIT 10;"
