# ブランド名＆カラーコード
SELECT_WHERE_BRAND_COLORCODE = "SELECT * FROM RIP_MASTER WHERE BRAND_NAME = %(brandName)s AND COLORCODE = %(colorCode)s AND HIDDEN_FLAG != '1';"
# 類似色
SELECT_WHERE_SIMILAR_COLORCODE = "SELECT * FROM RIP_MASTER WHERE (COLORCODE >= %(downVCode)s AND COLORCODE <= %(upVCode)s) OR (COLORCODE >= %(downSCode)s AND COLORCODE <= %(upSCode)s) AND HIDDEN_FLAG != '1';"